spring:
  datasource:
    url: jdbc:h2:file:./data/datax
    driverClassName: org.h2.Driver
    username: sa
    password: peakanime123$
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
          ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  h2:
    console:
      enabled: false
server:
  port: 5000

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

